---

- name: set swap file location and size
  set_fact:
    swap_file: /swapfile
    swap_size: "{{ ansible_memtotal_mb }}m"

- name: check if swap file exists
  stat: path={{ swap_file }}
  register: swap_file_check

- name: create swap file
  command: fallocate -l {{ swap_size }} {{ swap_file }}
  sudo: yes
  when: not swap_file_check.stat.exists

- name: set permissions on swap file
  file: path={{ swap_file }} mode=0600
  sudo: yes

- name: format swap file
  command: mkswap {{ swap_file }}
  sudo: yes
  when: not swap_file_check.stat.exists

- name: add to fstab
  lineinfile: dest=/etc/fstab
    regexp={{ swap_file }}
    line="{{ swap_file }} none swap sw 0 0"
  sudo: yes

- name: check if swap is on
  command: swapon -s
  changed_when: False
  sudo: yes
  register: swap_on_check

- name: turn swap on
  command: swapon -a
  sudo: yes
  when: swap_on_check.stdout.find("{{ swap_file }}") == -1

- name: set swapiness
  sysctl: name=vm.swappiness value=10 state=present
  sudo: yes

- name: set vfs cache pressure
  sysctl: name=vm.vfs_cache_pressure value=50 state=present
  sudo: yes
