- name: add users
  user: name="{{ item.username }}"
        comment="{{ item.comment }}"
        groups="{{ item.groups }}"
        password="{{ item.password }}"
        shell=/bin/bash
        state=present
  with_items: users

- name: add public keys
  authorized_key: user="{{ item.0.username }}"
                  key="{{ item.1 }}"
                  state=present
  with_subelements:
    - users
    - keys
