---

- name: update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes

- name: restart sshd
  service: name=ssh state=restarted enabled=yes
  sudo: yes

- name: restore firewall rules
  shell: "iptables-restore < /etc/iptables.firewall.rules"
  sudo: yes

- name: enable firewall
  service: name=iptables enabled=yes
  sudo: yes
