---

- name: update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart sshd
  service: name=ssh state=restarted enabled=yes

- name: restore iptables common
  shell: /sbin/iptables-restore < /etc/iptables.rules
