---

- name: set hostname
  hostname: name="{{ hostname }}"
  sudo: yes

- name: update /etc/hosts
  lineinfile: dest=/etc/hosts
              regexp="^127\.0\.1\.1"
              line="127.0.1.1 {{ hostname }}"
              owner=root
              group=root
              mode=0644
  sudo: yes


- name: upgrade packages
  apt: upgrade=dist update_cache=yes
  sudo: yes

- name: install packages
  apt: name="{{ item }}" update_cache=yes state=installed
  sudo: yes
  with_items:
    - iptables
    - vim

- name: create iptables rules
  copy: src=iptables.rules
        dest=/etc/iptables.firewall.rules
        owner=root
        group=root
        mode=0644
  sudo: yes
  notify:
    - restore firewall rules

- name: create iptables init script
  copy: src=iptables.init
        dest=/etc/network/if-pre-up.d/firewall
        owner=root
        group=root
        mode=0755
  sudo: yes

- name: set /etc/timezone to UTC
  copy: content=Etc/UTC
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  sudo: yes
  notify:
    - update tzdata

- name: create sshd_config
  copy: src=sshd_config
        dest=/etc/ssh/sshd_config
        owner=root
        group=root
        mode=0644
  sudo: yes
  notify:
    - restart sshd
