---

- name: install base packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present

- name: set timezone to UTC
  timezone:
    name: UTC
  notify:
    - update tzdata

- name: create sshd_config
  copy: src=sshd_config
        dest=/etc/ssh/sshd_config
        owner=root
        group=root
        mode=0644
  notify:
    - restart sshd

- include: firewall.yml
